config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: "users/sessions"
  }
  root to: 'home#index'
  resources :users do
    resources :body_temperatures do
    end
  end
  resources :groups do
    collection do
      get :add_member_new
      post :add_member_create
      get :send_mail
    end
    resources :users do
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/body_temperature.rb
class BodyTemperature < ApplicationRecord
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  has_many :body_temperatures, dependent: :destroy

  enum gender: ['男性', '女性', 'その他']

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        name:  auth.info.name,
        password: Devise.friendly_token[0, 20],
        image:  auth.info.image
      )
    end

    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/body_temperatures_controller.rb
class BodyTemperaturesController < ApplicationController
  def index
    @user = User.find(current_user.id)
  end

  def new
    @body_temperature = BodyTemperature.new
  end

  def create
    user = User.find(params[:user_id])
    bt = params[:body_temperature][:body_temperature]
    comment = params[:body_temperature][:comment]
    @body_temperature = user.body_temperatures.new(body_temperature: bt, comment: comment)
    if @body_temperature.save
      render 'index'
    else
      render 'new'
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new()
  end

  def create
    group = Group.create(create_params)
    user = User.find(current_user.id)
    user.group_id = group.id
    user.save
    redirect_to group_path(group.id)
  end

  def show
    @group = Group.find_by(role_id: current_user.id)
    @users = User.where(group_id: @group.id)
  end

  def add_member_new
  end

  def add_member_create
    user = User.find_by(email: params[:email])
    user.group_id = current_user.group_id
    user.save
    redirect_to group_path(current_user.group_id)
  end

  def send_mail
    # InquiryMailer.send_mail(user).deliver_now
  end

  private
  def create_params
    params.require(:group).permit(:name, :user_id, :role_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  def google
    callback_from :google_oauth2
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  protected

  def configure_permitted_parameters
    added_attrs = [ :name, :email, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(update_params)
      flash[:success] = 'ユーザー情報を編集しました。'
      redirect_to user_path(@user.id)
    else
      flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
      render :edit
    end
  end

  private

  def update_params
    params.require(:user).permit(:gender, :age, :height, :weight)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/body_temperature_helper.rb
module BodyTemperatureHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/body_temperatures/index.html.erb
<div class="section full mt-2 mb-2">
    <div class="section-title">Home</div>
    <div class="wide-block pt-2 pb-2">
        <div class='row'>
            <div class="col-12">
                <canvas id="myChart" width="400" height="250"></canvas>
                <br>
                <script>
                    var ctx = document.getElementById('myChart').getContext('2d');
                    var myChart = new Chart(ctx, {
                        type: 'line',
                        data: {
                            labels: ['4-1', '4-2', '4-3', '4-4', '4-5', '4-6'],
                            datasets: [{
                                data: [35.0, 36.3, 36, 38, 39, 38],
                                backgroundColor: [
                                    'rgba(255, 99, 132, 0.2)',
                                ],
                                borderColor: [
                                    'rgba(255, 99, 132, 1)',
                                ],
                                borderWidth: 1
                            }]
                        },
                        options: {
                            legend: { display: false },
                            scales: {
                                yAxes: [{
                                    ticks: {
                                        beginAtZero: false,
                                        min: 33,
                                        max: 40
                                    }
                                }]
                            }
                        }
                    });
                </script>
            </div>
        </div>
        <div class='row'>
            <div class="col-12">
                <%= link_to new_user_body_temperature_path do %>
                    <%= image_tag 'buttons/add_btn.png', class:"rounded mx-auto d-block"%>
                    <h4 class="blockquote text-center">体温を入力</h4>
                <% end %>
            </div>
        </div>
        <br>
        <div class='row'>
            <div class="col-12">
                <%= link_to new_user_body_temperature_path do%>
                    <%= image_tag 'buttons/edit_btn.png', class:"rounded mx-auto d-block" %>
                    <h4 class="blockquote text-center">体温を修正</h4>
                <% end %>
            </div>
        </div>
        <br>
        <div class='row'>
            <div class="col-12">
                <%= link_to new_group_path do %>
                    <%= image_tag 'buttons/team_btn.png', class:"rounded mx-auto d-block" %>
                    <h4 class="blockquote text-center">チームを作成</h4>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/body_temperatures/new.html.erb
<div class="section full mt-2 mb-2">
  <div class="section-title">Home</div>
  <div class="wide-block pt-2 pb-2">
    <div class='row'>
      <div class="col-12">
        <%= form_for @body_temperature, url: {action: "create"} do |f| %>
          <div class="form-group boxed">
              <div class="input-wrapper">
                <label class="label" for="name1">体温</label>
                <%= f.text_field :body_temperature, class:'form-control', id:'bt', placeholder:'体温を入力してください' %>
                <i class="clear-input">
                    <ion-icon name="close-circle"></ion-icon>
                </i>
              </div>
          </div>
          <div class="form-group boxed">
              <div class="input-wrapper">
                <label class="label" for="name1">コメント</label>
                <%= f.text_area :comment, class:'form-control', id:'bt', placeholder:'体調について特記事項' %>
                <i class="clear-input">
                  <ion-icon name="close-circle"></ion-icon>
                </i>
              </div>
          </div>
          <%= f.submit "登録する", class:'btn btn-primary btn-lg btn-block' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/add_member_create.html.erb
完了

app/views/groups/add_member_new.html.erb
<div class="section full mt-2 mb-2">
  <div class="m-2">
    <%= form_tag(add_member_create_groups_path, method: :post) do %>
      <div class="form-group">
        <%= label_tag :メールアドレス %>
        <%= text_field_tag :email, '', class: 'form-control' %>
        <%= submit_tag "追加", class: 'btn btn-dark mx-auto d-block mt-2' %>
    <% end %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="section full mt-2 mb-2">
  <div class="m-2">
    <%= form_for(@group) do |form| %>
      <div class="form-group">
        <%= form.label :チーム名 %>
        <%= form.text_field :name, class: 'form-control' %>
        <%= form.hidden_field(:user_id, :value => current_user.id) %>
        <%= form.hidden_field(:role_id, :value => current_user.id) %>
      </div>
      <div class="actions">
        <%= form.submit 'チーム作成', class: 'btn btn-dark mx-auto d-block' %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="section full mt-2 mb-2">
  <div class="m-2">
    <div class="section-title">確認連絡を送りました</div>
    <%= link_to 'ホームに戻る', group_path(current_user.group_id), class: 'btn btn-dark mx-auto d-block pt-1 mt-3' %>
  </div>
</div>

app/views/groups/show.html.erb
<div class="section full mt-2 mb-2">
  <div class="m-2">
    <span class="font-weight-bold">
      <%= @group.name %>
    </span>
    <div>チームリーダー : <%= current_user.name %></div>
  </div>
  <%= link_to 'メンバー追加', add_member_new_groups_path, class: 'btn btn-dark ml-2' %>

  <div class="wide-block pt-2 pb-2 mt-3">
    <p>チームメンバー</p>
    <% @users.each do |user| %>
      <p class="font-weight-bold mb-0 mt-2"><%= user.name %></p>
      <span><%= user.email %></span>
      <%= link_to 'アラート', send_mail_groups_path, class: 'btn-sm btn-danger' %>
    <% end %>

  </div>
</div>

app/views/home/index.html.erb
<div class="section full mt-2 mb-2">
    <div class="wide-block pt-2 pb-2">
        <div class='row'>
            <div class="col-12">
              <%= link_to 'Log in with Google', user_google_omniauth_authorize_path, class: "btn btn-light btn-lg btn-block"%>
            </div>
        </div>
        <br>
        <div class='row'>
            <div class="col-12">
              <%= link_to 'Log in with Facebook', user_facebook_omniauth_authorize_path, class: "btn btn-primary btn-lg btn-block"%>
            </div>
        </div>
        <br>
        <div class='row'>
            <div class="col-12">
                <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success btn-lg btn-block"%>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SaMo</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport"
        content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="theme-color" content="#000000">
    <meta name="description" content="Mobilekit HTML Mobile UI Kit">
    <meta name="keywords" content="bootstrap 4, mobile template, cordova, phonegap, mobile, html" />
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/icon/192x192.png">
    <!-- Ionicons -->
    <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- loader -->
    <div id="loader">
        <div class="spinner-border text-primary" role="status"></div>
    </div>
    <!-- App Header -->
    <div class="appHeader text-light">
        <div class="left"></div>
        <div class="pageTitle">
            <%= image_tag 'thermo.png' %>
        </div>
        <div class="right"></div>
        </div>
    </div>
    <!-- * App Header -->
    <!-- App Capsule -->
    <div id="appCapsule">
      <%= yield %>
      <!-- iOS Add to Home Action Sheet -->
      <div class="modal inset fade action-sheet ios-add-to-home" id="ios-add-to-home-screen" tabindex="-1"
          role="dialog">
          <div class="modal-dialog" role="document">
              <div class="modal-content">
                  <div class="modal-header">
                      <h5 class="modal-title">Add to Home Screen</h5>
                      <a href="javascript:;" class="close-button" data-dismiss="modal">
                          <ion-icon name="close"></ion-icon>
                      </a>
                  </div>
                  <div class="modal-body">
                      <div class="action-sheet-content text-center">
                          <div class="mb-1"><img src="/assets/icon/192x192.png" alt="image" class="imaged w48">
                          </div>
                          <h4>Mobilekit</h4>
                          <div>
                              Install Mobilekit on your iPhone's home screen.
                          </div>
                          <div>
                              Tap <ion-icon name="share-outline"></ion-icon> and Add to homescreen.
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
      <!-- * iOS Add to Home Action Sheet -->
      <!-- Android Add to Home Action Sheet -->
      <div class="modal inset fade action-sheet android-add-to-home" id="android-add-to-home-screen" tabindex="-1"
          role="dialog">
          <div class="modal-dialog" role="document">
              <div class="modal-content">
                  <div class="modal-header">
                      <h5 class="modal-title">Add to Home Screen</h5>
                      <a href="javascript:;" class="close-button" data-dismiss="modal">
                          <ion-icon name="close"></ion-icon>
                      </a>
                  </div>
                  <div class="modal-body">
                      <div class="action-sheet-content text-center">
                          <div class="mb-1"><img src="/assets/icon/192x192.png" alt="image" class="imaged w48">
                          </div>
                          <h4>Mobilekit</h4>
                          <div>
                              Install Mobilekit on your Android's home screen.
                          </div>
                          <div>
                              Tap <ion-icon name="ellipsis-vertical"></ion-icon> and Add to homescreen.
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
      <!-- * Android Add to Home Action Sheet -->
      <!-- App Bottom Menu -->
      <div class="appBottomMenu">
          <%= link_to root_path, class: 'item' do %>
              <div class="col">
                  <ion-icon name="home-outline"></ion-icon>
              </div>
          <% end %>
          <a href="/" class="item">
            <div class="col">
                <ion-icon name="person-outline"></ion-icon>
            </div>
          </a>
      </div>
      <!-- * App Bottom Menu -->
      <!-- App Sidebar -->
      <div class="modal fade panelbox panelbox-left" id="sidebarPanel" tabindex="-1" role="dialog">
          <div class="modal-dialog" role="document">
              <div class="modal-content">
                  <div class="modal-body p-0">
                      <!-- profile box -->
                      <div class="profileBox">
                          <div class="image-wrapper">
                              <%= image_tag 'sample/avatar/avatar1.jpg' %>
                          </div>
                          <div class="in">
                              <strong>Julian Gruber</strong>
                              <div class="text-muted">
                                  <ion-icon name="location"></ion-icon>
                                  California
                              </div>
                          </div>
                          <a href="javascript:;" class="close-sidebar-button" data-dismiss="modal">
                              <ion-icon name="close"></ion-icon>
                          </a>
                      </div>
                      <!-- * profile box -->
    
                      <ul class="listview flush transparent no-line image-listview mt-2">
                          <li>
                              <a href="index.html" class="item">
                                  <div class="icon-box bg-primary">
                                      <ion-icon name="home-outline"></ion-icon>
                                  </div>
                                  <div class="in">
                                      Discover
                                  </div>
                              </a>
                          </li>
                          <li>
                              <a href="app-components.html" class="item">
                                  <div class="icon-box bg-primary">
                                      <ion-icon name="cube-outline"></ion-icon>
                                  </div>
                                  <div class="in">
                                      Components
                                  </div>
                              </a>
                          </li>
                          <li>
                              <a href="app-pages.html" class="item">
                                  <div class="icon-box bg-primary">
                                      <ion-icon name="layers-outline"></ion-icon>
                                  </div>
                                  <div class="in">
                                      <div>Pages</div>
                                  </div>
                              </a>
                          </li>
                          <li>
                              <a href="page-chat.html" class="item">
                                  <div class="icon-box bg-primary">
                                      <ion-icon name="chatbubble-ellipses-outline"></ion-icon>
                                  </div>
                                  <div class="in">
                                      <div>Chat</div>
                                      <span class="badge badge-danger">5</span>
                                  </div>
                              </a>
                          </li>
                          <li>
                              <div class="item">
                                  <div class="icon-box bg-primary">
                                      <ion-icon name="moon-outline"></ion-icon>
                                  </div>
                                  <div class="in">
                                      <div>Dark Mode</div>
                                      <div class="custom-control custom-switch">
                                          <input type="checkbox" class="custom-control-input dark-mode-switch"
                                              id="darkmodesidebar">
                                          <label class="custom-control-label" for="darkmodesidebar"></label>
                                      </div>
                                  </div>
                              </div>
                          </li>
                      </ul>
    
                      <div class="listview-title mt-2 mb-1">
                          <span>Friends</span>
                      </div>
                      <ul class="listview image-listview flush transparent no-line">
                          <li>
                              <a href="page-chat.html" class="item">
                                  <%= image_tag 'sample/avatar/avatar7.jpg' %>
                                  <div class="in">
                                      <div>Sophie Asveld</div>
                                  </div>
                              </a>
                          </li>
                          <li>
                              <a href="page-chat.html" class="item">
                                  <%= image_tag 'sample/avatar/avatar3.jpg' %>
                                  <div class="in">
                                      <div>Sebastian Bennett</div>
                                      <span class="badge badge-danger">6</span>
                                  </div>
                              </a>
                          </li>
                          <li>
                              <a href="page-chat.html" class="item">
                                  <%= image_tag 'sample/avatar/avatar10.jpg' %>
                                  <div class="in">
                                      <div>Beth Murphy</div>
                                  </div>
                              </a>
                          </li>
                          <li>
                              <a href="page-chat.html" class="item">
                                  <%= image_tag 'sample/avatar/avatar2.jpg' %>
                                  <div class="in">
                                      <div>Amelia Cabal</div>
                                  </div>
                              </a>
                          </li>
                          <li>
                              <a href="page-chat.html" class="item">
                                  <%= image_tag 'sample/avatar/avatar5.jpg' %>
                                  <div class="in">
                                      <div>Henry Doe</div>
                                  </div>
                              </a>
                          </li>
                      </ul>
    
                  </div>
    
                  <!-- sidebar buttons -->
                  <div class="sidebar-buttons">
                      <a href="javascript:;" class="button">
                          <ion-icon name="person-outline"></ion-icon>
                      </a>
                      <a href="javascript:;" class="button">
                          <ion-icon name="archive-outline"></ion-icon>
                      </a>
                      <a href="javascript:;" class="button">
                          <ion-icon name="settings-outline"></ion-icon>
                      </a>
                      <a href="javascript:;" class="button">
                          <ion-icon name="log-out-outline"></ion-icon>
                      </a>
                  </div>
                  <!-- * sidebar buttons -->
              </div>
          </div>
      </div>
      <!-- * App Sidebar -->
    </div>
    <!-- * App Capsule -->
  </body>
</html>

app/views/users/edit.html.erb
<div class="section full mt-2 mb-2">
  <div class="wide-block pt-2 pb-2">
    <div class='row'>
      <div class="col-6 align-self-center">
        <div class="text-center">
          <% if @user.image %>
            <%= image_tag @user.image %>
           <% end %>
        </div>
      </div>
      <div class="col-6">
        <div>
          <%= @user.name %>
        </div>
        <div>
          <%= @user.email %>
        </div>
      </div>
      <div class="col-12">
        <%= form_for @user do |f| %>
          <label class="label" for="name1">性別</label>
          <%= f.select :gender, User.genders.keys.map {|k| [k, k]}, {}, { class:'form-control', id:'bt' } %>
          <label class="label" for="name1">年齢</label>
          <%= f.text_field :age, class:'form-control', id:'bt', placeholder:'35' %><br />
          <label class="label" for="name1">身長</label>
          <%= f.text_field :height, class:'form-control', id:'bt', placeholder:'170' %><br />
          <label class="label" for="name1">体重</label>
          <%= f.text_field :weight, class:'form-control', id:'bt', placeholder:'65' %><br />
          <%= f.submit '登録する', class:'btn btn-primary btn-lg btn-block' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="section full mt-2 mb-2">
  <div class="wide-block pt-2 pb-2">
    <div class='row'>
      <div class="col-6 align-self-center">
        <div class="text-center">
          <% if @user.image %>
            <%= image_tag @user.image %>
           <% end %>
        </div>
      </div>
      <div class="col-6">
        <div>
          <%= @user.name %>
        </div>
        <div>
          <%= @user.email %>
        </div>
      </div>
      <div class="col-12">
        <label class="label" for="name1">性別</label>
        <%= @user.gender %><br/>
        <label class="label" for="name1">年齢</label>
        <%= @user.age %><br/>
        <label class="label" for="name1">身長</label>
        <%= @user.height %><br/>
        <label class="label" for="name1">体重</label>
        <%= @user.weight %><br/>
        <%= link_to "編集する", edit_user_path, class:'btn btn-primary btn-lg btn-block' %>
        </div>
    </div>
  </div>
</div>